---
opsman-configuration:
  aws:
    access_key_id: ((/concourse/main/access_key_id))
    secret_access_key: ((/concourse/main/secret_access_key))
    region: eu-west-1
    vm_name: ops-manager-vm                           # default: OpsManager-vm
    boot_disk_size: 100                               # default 200
    vpc_subnet_id: subnet-034ca56f8ae93f0b4
    security_group_id: sg-07d116615e4fb3b56
    key_pair_name: pas-ops-manager-key
    iam_instance_profile_name: ops-manager-iam
    instance_type: m5.large
    # At least one IP address (public or private) needs to be assigned to the VM.
    public_ip: 63.34.167.60
    # private_ip: 10.0.0.2