---
opsman-configuration:
  aws:
    access_key_id: ((/concourse/main/access_key_id))
    secret_access_key: ((/concourse/main/secret_access_key))
    region: eu-west-1
    vm_name: ops-manager-vm                           # default: OpsManager-vm
    boot_disk_size: 100                               # default 200
    vpc_subnet_id: subnet-0e4240079f797e99e
    security_group_id: sg-01743ab39ea22a859
    key_pair_name: pas-ops-manager-key
    iam_instance_profile_name: pas_ops_manager
    instance_type: r4.large
    # At least one IP address (public or private) needs to be assigned to the VM.
    public_ip: 34.242.195.157
    # private_ip: 10.0.0.2