---
pas_skip_cert_verify: true
pas_mysql_email: siobrien@pivotal.io
pas_credhub_key: ((/concourse/main/pas_credhub_key))
pas_blobstore_s3_access_key_id: ((/concourse/main/access_key_id))
pas_blobstore_s3_access_key_secret: ((/concourse/main/secret_access_key))