---
opsman-configuration:
  aws:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: {{.region}}
    vm_name: ((vm_name))
    boot_disk_size: ((boot_disk_size))
    vpc_subnet_id: {{index .public_subnet_ids 0}}
    security_group_id: {{.ops_manager_security_group_id}}
    key_pair_name: {{.ops_manager_ssh_public_key_name}}
    iam_instance_profile_name: {{.ops_manager_iam_instance_profile_name}}
    instance_type: ((instance_type))
    public_ip: {{.ops_manager_public_ip}}