product-name: cf
product-properties:
  .cloud_controller.apps_domain:
    value: {{.apps_domain}}
  .cloud_controller.system_domain:
    value: {{.apps_domain}}
  .ha_proxy.skip_cert_verify:
    value: ((pas_skip_cert_verify))
  .mysql_monitor.recipient_email:
    value: ((pas_mysql_email))
  .properties.credhub_key_encryption_passwords:
    value:
    - name: credhub-key
      primary: true
      provider: internal
      key:
        secret: ((pas_credhub_key))
  .properties.haproxy_forward_tls:
    value: disable
  .properties.networking_poe_ssl_certs:
    value:
    - certificate:
        cert_pem: |
{{indent 10 .ssl_cert}}
        private_key_pem: |
{{indent 10 .ssl_private_key}}
      name: Certificate
  .properties.security_acknowledgement:
    value: X
  .properties.system_blobstore:
    value: external
  .properties.system_blobstore.external.access_key:
    value: ((pas_blobstore_s3_access_key_id))
  .properties.system_blobstore.external.secret_key:
    value:
      secret: ((pas_blobstore_s3_access_key_secret))
  .properties.system_blobstore.external.buildpacks_bucket:
    value: {{.pas_buildpacks_bucket}}
  .properties.system_blobstore.external.droplets_bucket:
    value: {{.pas_droplets_bucket}}
  .properties.system_blobstore.external.endpoint:
    value: https://s3.{{.region}}.amazonaws.com
    # value: ((pas_blobstore_s3_endpoint))
  .properties.system_blobstore.external.packages_bucket:
    value: {{.pas_packages_bucket}}
  .properties.system_blobstore.external.region:
    value: {{.region}}
  .properties.system_blobstore.external.resources_bucket:
    value: {{.pas_resources_bucket}}
  .uaa.service_provider_key_credentials:
    value:
      cert_pem: |
{{indent 8 .ssl_cert}}
      private_key_pem: |
{{indent 8 .ssl_private_key}}
network-properties:
  network:
    name: pas-ert-network
  other_availability_zones:
    {{range .azs}}
    - name: {{.}}
    {{end}}
  singleton_availability_zone:
    name: {{index .azs 0}}
resource-config:
  diego_brain:
    elb_names:
    {{range .ssh_target_groups}}
    - alb:{{.}}
    {{end}}
    additional_vm_extensions:
    - ssh-lb-security-groups
  router:
    elb_names:
    {{range .web_target_groups}}
    - alb:{{.}}
    {{end}}
    additional_vm_extensions:
    - web-lb-security-groups
  tcp_router:
    elb_names:
    {{range .tcp_target_groups}}
    - alb:{{.}}
    {{end}}
    additional_vm_extensions:
    - tcp-lb-security-groups