---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: 1.0.20
inputs:
  - name: terraform-state
  - name: aws-terraform
  - name: pcf-aws-automation
outputs:
  - name: terraform-state-output
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_REGION:
run:
  path: pcf-aws-automation/tasks/destroy-aws/task.sh
