---
resource_types:

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tags: latest-final

resources:

- name: pcf-aws-automation
  type: git
  source:
    private_key: ((git-key.private_key))
    uri: ((automation_repo))
    branch: master

- name: opsman-product
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((aws_region))
    bucket: ((artifacts_bucket))
    regexp: OpsManager(.*)onAWS.yml

- name: pas-product
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((aws_region))
    bucket: ((artifacts_bucket))
    regexp: cf-(.*).pivotal

- name: pas-stemcell
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((aws_region))
    bucket: ((artifacts_bucket))
    regexp: pas-stemcell/bosh-stemcell-(.*)-vsphere.*\.tgz

- name: pcf-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet-token))
    product_slug: platform-automation
    product_version: 1\.(.*) # pin to major version 1
    sort_by: semver

- name: pcf-automation-tasks
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((aws_region))
    bucket: ((artifacts_bucket))
    regexp: platform-automation-tasks-(.*).zip

- name: pcf-automation-image
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((aws_region))
    bucket: ((artifacts_bucket))
    regexp: platform-automation-image-(.*).tgz

jobs:

- name: fetch-pas
  plan:
  - aggregate:
    - get: pcf-automation-image
      params:
        unpack: true
    - get: pcf-automation-tasks
      params:
        unpack: true
    - get: pcf-aws-automation
  - task: credhub-interpolate
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: ((credhub-server))
      CREDHUB_CA_CERT: ((credhub-ca.certificate))
      PREFIX: '/'
      INTERPOLATION_PATH: 'config/pivnet'
    input_mapping:
      files: pcf-aws-automation
    output_mapping:
      interpolated-files: pcf-aws-automation-interpolated
  - task: download-pas-product-and-stemcell
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: config/pivnet/pas.yml
    input_mapping:
      config: pcf-aws-automation-interpolated
    output_mapping:
      downloaded-stemcell: pas-stemcell
  - aggregate:
    - put: pas-product
      params:
        file: downloaded-product/*.pivotal
    - put: pas-stemcell
      params:
        file: pas-stemcell/*.tgz

- name: fetch-opsman
  plan:
  - aggregate:
    - get: pcf-automation-image
      params:
        unpack: true
    - get: pcf-automation-tasks
      params:
        unpack: true
    - get: pcf-aws-automation
  - task: credhub-interpolate
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: ((credhub-server))
      CREDHUB_CA_CERT: ((credhub-ca.certificate))
      PREFIX: '/'
      INTERPOLATION_PATH: 'config/pivnet'
    input_mapping:
      files: pcf-aws-automation
    output_mapping:
      interpolated-files: pcf-aws-automation-interpolated
  - task: download-opsman-image
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: config/pivnet/opsman.yml
    input_mapping:
      config: pcf-aws-automation-interpolated
  - aggregate:
    - put: opsman-product
      params:
        file: downloaded-product/*

- name: fetch-platform-automation
  plan:
  - get: pcf-automation-pivnet
  - aggregate:
    - put: pcf-automation-tasks
      params:
        file: pcf-automation-pivnet/*tasks*.zip
    - put: pcf-automation-image
      params:
        file: pcf-automation-pivnet/*image*.tgz