---
resources:

- name: aws-terraform
  type: git
  source:
    uri: ((terraform_repo))
    branch: master

- name: pcf-aws-automation
  type: git
  source:
    uri: ((automation_repo))
    branch: master

jobs:

- name: pave-iaas
  plan:
  - aggregate:
    - get: pcf-aws-automation
    - get: aws-terraform

  - task: create-infrastructure
    file: pcf-aws-automation/tasks/prepare-aws-test/task.yml
    params:
      ENV_NAME: ((env_name))
      AWS_ACCESS_KEY_ID: ((access_key_id))
      AWS_SECRET_ACCESS_KEY: ((secret_access_key))
      AWS_SESSION_TOKEN: ((session_token))
      AWS_REGION: ((aws_region))