---
resources:

- name: aws-terraform
  type: git
  source:
    uri: ((terraform_repo))
    branch: master

- name: pcf-aws-automation
  type: git
  source:
    private_key: ((git-key.private_key))
    uri: ((automation_repo))
    branch: master

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((aws_region))
    bucket: ((artifacts_bucket))
    regexp: platform-automation-image-(.*).tgz

jobs:

- name: pave-iaas
  plan:
  - aggregate:
    - get: pcf-aws-automation
    - get: aws-terraform
    - get: platform-automation-image
      params:
        unpack: true

  - task: create-infrastructure
    file: pcf-aws-automation/tasks/prepare-aws-test/task.yml
    params:
      ENV_NAME: ((env_name))
      AWS_ACCESS_KEY_ID: ((access_key_id))
      AWS_SECRET_ACCESS_KEY: ((secret_access_key))
      AWS_REGION: ((aws_region))