---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: 1.0.20
inputs:
  - name: terraform-state
  - name: ami
  - name: aws-terraform
  - name: pcf-aws-automation
outputs:
  - name: terraform-state-output
params:
  ENV_NAME:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_REGION:
  AWS_AZ1:
  AWS_AZ2:
  AWS_AZ3:
  HOSTED_ZONE:
  DNS_SUFFIX:
  VPC_CIDR:
run:
  path: pcf-aws-automation/tasks/prepare-aws/task.sh
